### ISSUE TITLE
Help, this does not seem to work for me

### ISSUE THREAD

**Issue by jasikpark** [jonahsnider/netlify-plugin-cache-yarn2#29]
I have this setup in https://github.com/jasikpark/jasik-xyz, and I do not see a large difference in build times before and after adding the cache, in addition, it seems to run in the log *after* Netlify installs the packages using Yarn 2, or is the logging non-linear?

**Comment by jonahsnider** [comment]
Like you'd said the plugin seems to run *after* the Netlify package install which makes it useless. Unless Netlify changes that behavior the plugin won't actually do anything.

**Comment by jasikpark** [comment]
Ouch, that sucks. Thanks for working on this though! I definitely wish Netlify had support for directly caching the Yarn 2 version instead of installing from Yarn 1 on each run.

**Comment by jonahsnider** [comment]
Yeah, I [opened a ticket](https://answers.netlify.com/t/yarn-2-needs-proper-support-in-builds/30442) months ago asking for official support which received some replies from Netlify engineers. I'm a bit annoyed they still haven't added support for it or even given a timeline on their progress.
